### ISSUE TITLE
Recursive Documentation for Rails

### ISSUE THREAD

**Issue by cguess** [redis-store/redis-actionpack#30]
The documentation here states
> For information on how to use this library in a Rails app, see the documentation for redis-rails.

However, the documentation on `redis-rails` says
> We are still actively maintaining all other gems in the redis-store family, such as redis-actionpack for session management

Which doesn't really clean up anything. Would it be possible to clarify these instructions?

**Comment by cguess** [comment]
Also documented at `redis-rails` here https://github.com/redis-store/redis-rails/issues/106

**Comment by tubbo** [comment]
I'm not quite sure what needs clarification here. The piece you quoted comes from the "quick note about Rails 5.2", in which Rails introduced a built-in Redis cache store. This somewhat obviated the need for a `redis-activesupport`, but the note there was to inform users about our maintenance plan going forward, in that `redis-activesupport` will only see security updates and bug fixes from now on. Gems like `redis-actionpack` and `redis-rack-cache` are still going to be fully supported, but since Rails comes with its own Redis cache store, we aren't going to be maintaining a competing library since that isn't really productive.

**Comment by tubbo** [comment]
I'm gonna close this due to inactivity, and will assume my documentation is perfect :)
